version: '3.1'

services:
  apache:
    build:
      context: ./apache
      args:
        - POTTO_PHP_VERSION=${POTTO_PHP_VERSION}
        - POTTO_PUID=${POTTO_PUID}
    volumes:
      - ${POTTO_APPLICATION}:/var/www
    ports:
      - ${POTTO_HTTP_PORT}:80
  php:
    build:
      context: ./php
      args:
        - POTTO_PHP_VERSION=${POTTO_PHP_VERSION}
        - POTTO_PUID=${POTTO_PUID}
    volumes:
      - ${POTTO_APPLICATION}:/var/www
  node:
    build:
      context: ./node
      args:
        - POTTO_NODE_VERSION=${POTTO_NODE_VERSION}
        - POTTO_PUID=${POTTO_PUID}
    volumes:
      - ${POTTO_APPLICATION}:/app
  db:
    build:
      context: ./db
      args:
        - POTTO_MYSQL_VERSION=${POTTO_MYSQL_VERSION}
        - POTTO_PUID=${POTTO_PUID}
    volumes:
      - ${POTTO_STORAGE}/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${POTTO_MYSQL_PASSWORD}
  redis:
    image: redis
