version: '3.1'

services:
  apache:
    build:
      context: ./apache
      args:
        - PHP_VERSION=${PHP_VERSION}
        - USER_UID=${USER_UID}
    volumes:
      - ${APPLICATION}:/var/www
    ports:
      - ${HTTP_PORT}:80
  php:
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - USER_UID=${USER_UID}
    volumes:
      - ${APPLICATION}:/var/www
  node:
    build:
      context: ./node
      args:
        - NODE_VERSION=${NODE_VERSION}
        - USER_UID=${USER_UID}
    volumes:
      - ${APPLICATION}:/app
  db:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - ${STORAGE}/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
  redis:
    image: redis
